CREATE DATABASE laboratory_db;

CREATE TABLE admins(IDAdmin INT PRIMARY KEY AUTO_INCREMENT, adminCode INT NOT NULL, adminFullname VARCHAR(50) NOT NULL, 
adminDni VARCHAR(8) NOT NULL, adminEmail VARCHAR(225) NOT NULL, adminPassword VARCHAR(100) NOT NULL, adminAvatar MEDIUMBLOB NOT NULL,
adminCreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE employees(IDEmployee INT PRIMARY KEY AUTO_INCREMENT, employeeCode INT NOT NULL, employeeFullname VARCHAR(50) NOT NULL, 
employeeDni VARCHAR(8) NOT NULL, employeeEmail VARCHAR(225) NOT NULL, employeePassword VARCHAR(100) NOT NULL, employeeAddress VARCHAR(100) NOT NULL,
employeeAvatar MEDIUMBLOB NOT NULL, employeeCreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE peopleExams(IDPeopleExams INT PRIMARY KEY AUTO_INCREMENT, peopleFullname VARCHAR(100) NOT NULL, peopleDni VARCHAR(8) NOT NULL,
peopleEmail VARCHAR(255) NOT NULL, peopleExamsCategory VARCHAR(50) NOT NULL, peopleExamsName VARCHAR(50) NOT NULL, peopleExamsPrice FLOAT NOT NULL,
peopleExamsResult TEXT, peopleExamsPaymentStatus BOOLEAN DEFAULT false NOT NULL, peopleExamsCreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE payments(IDPayment INT PRIMARY KEY AUTO_INCREMENT, IDPeopleExams INT NOT NULL, paymentCreatedAt TIMESTAMP
DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (IDPeopleExams) REFERENCES peopleExams(IDPeopleExams));